pipelines:
  GEM-pugin-component-ruby:
    group: Dependencies
    label_template: "${COUNT}"
    materials:
      GEM-pugin-component-ruby-git:
        git: https://github.com/ukparliament/parliament.uk-pugin-components-ruby.git
        branch: master
        auto_update: true
    stages:
      - deploy:
          approval: manual
          jobs:
            deploy:
              tasks:
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - checkout_to_release
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - deploy_to_release

environments:
  Web.LIVE:
    pipelines:
      - GEM-pugin-component-ruby
